//# sourceMappingURL=prefetchModule.js.map
var __FontVariant;(function(){__FontVariant=function(c){this._originalVariantString=c;var b=parseInt(c);this.weight=isNaN(b)?400:b;this.style=c.endsWith("i")?"italic":"normal"}})();var __FontFace;
(function(){__FontFace=function(b){this.fontFamily=b.fontFamily;this.fontWeight=b.fontWeight;this.fontStyle=b.fontStyle;this.src=b.src;this.unicodeRange=b.unicodeRange;this.fontDisplay=b.fontDisplay};var c=__FontFace.prototype;c.toFontFaceString=function(b){b=void 0===b?this.fontWeight:b;return"@font-face {font-family:'"+this.fontFamily+" "+b+" "+this.fontStyle+"';font-style:"+this.fontStyle+";font-weight:"+b+";font-display:"+this.fontDisplay+";src:"+this.src+";unicode-range:"+this.unicodeRange+";}"};
c.hasFontWeightRange=function(b){var a=this.fontWeight.split(" "),f=parseInt(a[0]),a=parseInt(a[a.length-1]);return b>=f&&b<=a};__FontFace.createFromString=function(b){var a=function(a){return null!==a&&0<a.length&&"string"===typeof a[1]?a[1].trim():""},f=a(b.match(/font-family:(.*?);/)).replace(/'/g,""),d=a(b.match(/font-weight:(.*?);/)),c=a(b.match(/font-style:(.*?);/)),e=a(b.match(/src:(.*?);/));b=a(b.match(/unicode-range:(.*?);/));return new __FontFace({fontFamily:f,fontWeight:d,fontStyle:c,fontDisplay:"swap",
src:e,unicodeRange:b})}})();var GoogleFontService;
(function(){GoogleFontService=function(){};var c,b=GoogleFontService.prototype;b.fetchGoogleFontsCss=function(){var a=document.querySelector("script#googleFontsLinks"),b;if(null!==a){try{b=JSON.parse(a.textContent)}catch(d){b=[]}c=b.length;for(a=0;a<b.length;a++)this.fetchGoogleFontCssModifyAndAddToHeader(b[a])}};b.fetchGoogleFontCssModifyAndAddToHeader=function(a){var b=this,d=new XMLHttpRequest;d.open("GET",a,!0);d.onload=function(){200<=d.status&&400>d.status?b.modifyAndAppendFontCSSToDOM(d.responseText,
a):console.error("_fetchGoogleFont Request error. Url: "+a)};d.onerror=function(){console.error("_fetchGoogleFont Request error. Url: "+a)};d.send()};b.modifyAndAppendFontCSSToDOM=function(a,b){a=this.modifyFontFaceNames(a,b);this.appendCSSToDOM(a)};b.appendCSSToDOM=function(a){var b=document.createElement("STYLE");b.innerHTML=a;document.head.insertBefore(b,document.head.firstChild);0===--c&&(a=new CustomEvent("webwave.fontsLoadedEvent"),window.webwaveFontsLoadedFlag=!0,window.dispatchEvent(a))};
b.createFontFacesFromString=function(a){var b=[];a=a.match(/@font-face[\s\S]*?}/g);for(var d=0;d<a.length;d++)b.push(__FontFace.createFromString(a[d]));return b};b._getParamFromUrl=function(a,b){return(a=a.match(new RegExp(".*[?&]"+b+"=([^&'\"]+)(&|$|'|\")")))?a[1]:""};b._parseVariantsFromUrl=function(a){var b=[];a=this._getParamFromUrl(a,"family").split(":")[1];"undefined"===typeof a&&(a="400");a=a.split(",");for(var d=0;d<a.length;d++)b.push(new __FontVariant(a[d]));return b};b.modifyFontFaceNames=
function(a,b){var d="";a=this.createFontFacesFromString(a);b=this._parseVariantsFromUrl(b);for(var c=0;c<a.length;c++)for(var e=0;e<b.length;e++)a[c].fontStyle===b[e].style&&a[c].hasFontWeightRange(b[e].weight)&&(d+=a[c].toFontFaceString(b[e].weight));return d};(new GoogleFontService).fetchGoogleFontsCss()})();var SWLoader=function(){};SWLoader.prototype.init=function(){this.tryToCache(5)};
SWLoader.prototype.tryToCache=function(c){var b=this;if(!0===this._isNavigator()){var a=this;navigator.serviceWorker.getRegistrations().then(function(f){0<f.length?b.addFilesToCache():0<c&&(c--,setTimeout(function(){a.tryToCache(c)},1E3))})}};SWLoader.prototype._isNavigator=function(){return null!==navigator&&void 0!==navigator&&null!==navigator.serviceWorker&&void 0!==navigator.serviceWorker};
SWLoader.prototype.addFilesToCache=function(){for(var c=document.getElementsByClassName("pwaCacheableFile"),b=[],a=0;a<c.length;a++)null!==c[a].getAttribute("href")?b.push(c[a].getAttribute("href")):null!==c[a].getAttribute("src")&&b.push(c[a].getAttribute("src"));c=wwConfig.additionalResoucresUrl.iconFiles.replace("[","").replace("]","").split(",");for(a=0;a<c.length;a++)b.push(c[a]);b.push(document.location.pathname);caches.open("v1").then(function(a){for(var c={},g=0;g<b.length;c={k:c.k},g++)c.k=
g,a.match(b[g]).then(function(c){return function(d){d||a.add(b[c.k])}}(c))},function(a){console.log("Installation failed with error: "+a)})};(new SWLoader).init();